/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/add-form': RouteRecordInfo<'/add-form', '/add-form', Record<never, never>, Record<never, never>>,
    '/diagrams': RouteRecordInfo<'/diagrams', '/diagrams', Record<never, never>, Record<never, never>>,
    '/tables': RouteRecordInfo<'/tables', '/tables', Record<never, never>, Record<never, never>>,
  }
}
