/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddForm: typeof import('@/components/transaction-form/transaction-form.vue')['default']
    AppFooter: typeof import('./../components/appFooter.vue')['default']
    ButtonItems: typeof import('./../components/ui/button-items/button-items.vue')['default']
    ChartsController: typeof import('./../components/charts/charts-controller.vue')['default']
    DateField: typeof import('./../components/transaction-form/components/date-field.vue')['default']
    DatePicker: typeof import('@/components/transaction-form/components/date-picker.vue')['default']
    DiagramController: typeof import('@/components/charts/charts-controller.vue')['default']
    DomainsTabs: typeof import('./../components/domains-tabs/domains-tabs.vue')['default']
    DomainsTabsTemplate: typeof import('@/components/domains-tabs/domains-tabs.vue')['default']
    Form: typeof import('./../components/transaction-form/form.vue')['default']
    FormActions: typeof import('@/components/ui/button-items/button-items.vue')['default']
    GroupField: typeof import('./../components/transaction-form/components/group-field.vue')['default']
    IntervalSelection: typeof import('./../components/charts/settings/interval-selection.vue')['default']
    LineChart: typeof import('@/components/charts/custom-charts/radar-chart/radar-chart.vue')['default']
    RadarChart: typeof import('@/components/charts/custom-charts/radar-chart/radar-chart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchGroup: typeof import('@/components/transaction-form/components/search-group.vue')['default']
    Sidebar: typeof import('./../components/sidebar/sidebar.vue')['default']
    SumField: typeof import('./../components/transaction-form/components/sum-field.vue')['default']
    Table: typeof import('@/components/tables/tables.vue')['default']
    TableModal: typeof import('./../components/tables/table-modal/table-modal.vue')['default']
    Tables: typeof import('./../components/tables/tables.vue')['default']
    TransactionForm: typeof import('./../components/transaction-form/transaction-form.vue')['default']
    TransactionTable: typeof import('@/components/tables/tables.vue')['default']
  }
}
